version: "3"

services:
  json-server:
    build:
      context: serialization_server/
      dockerfile: server.Dockerfile
    command: python3 ./server.py
    environment:
      METHOD: JSON
      HOST: 0.0.0.0
      PORT: 1234
    ports:
      - 1234:1234
  
  messagepack-server:
    build:
      context: serialization_server/
      dockerfile: server.Dockerfile
    command: python3 ./server.py
    environment:
      METHOD: MessagePack
      HOST: 0.0.0.0
      PORT: 1235
    ports:
      - 1235:1235

  proxy:
    build:
      context: proxy/
      dockerfile: proxy.Dockerfile
    command: python3 ./proxy.py
    environment:
      HOST: 0.0.0.0
      PORT: 2000
      JSON: 1234
    ports: 
      - 2000:2000
    depends_on:
      - json-server
      - messagepack-server