version: "3"

services:
  json-server:
    build:
      context: serialization_server/
      dockerfile: server.Dockerfile
    command: python3 ./server.py
    environment:
      METHOD: JSON
      HOST: 0.0.0.0
      PORT: 2001
  
  messagepack-server:
    build:
      context: serialization_server/
      dockerfile: server.Dockerfile
    command: python3 ./server.py
    environment:
      METHOD: MessagePack
      HOST: 0.0.0.0
      PORT: 2002
  
  native-server:
    build:
      context: serialization_server/
      dockerfile: server.Dockerfile
    command: python3 ./server.py
    environment:
      METHOD: Native
      HOST: 0.0.0.0
      PORT: 2003
  
  yaml-server:
    build:
      context: serialization_server/
      dockerfile: server.Dockerfile
    command: python3 ./server.py
    environment:
      METHOD: YAML
      HOST: 0.0.0.0
      PORT: 2004
  
  xml-server:
    build:
      context: serialization_server/
      dockerfile: server.Dockerfile
    command: python3 ./server.py
    environment:
      METHOD: XML
      HOST: 0.0.0.0
      PORT: 2005

  proxy:
    build:
      context: proxy/
      dockerfile: proxy.Dockerfile
    command: python3 ./proxy.py
    environment:
      HOST: 0.0.0.0
      PORT: 4242
      JSON: 2001
      MESSAGEPACK: 2002
      NATIVE: 2003
      YAML: 2004
      XML: 2005
    ports: 
      - 4242:4242
    depends_on:
      - json-server
      - messagepack-server
      - native-server
      - yaml-server
      - xml-server