version: "3"

services:
  json-worker:
    build:
      context: serialization_worker/
      dockerfile: worker.Dockerfile
    command: python3 ./worker.py
    environment:
      METHOD: JSON
      HOST: 0.0.0.0
      PORT: $JSON_PORT
      MCAST_IP: $MCAST_IP
      MCAST_PORT: $MCAST_PORT
  
  messagepack-worker:
    build:
      context: serialization_worker/
      dockerfile: worker.Dockerfile
    command: python3 ./worker.py
    environment:
      METHOD: MessagePack
      HOST: 0.0.0.0
      PORT: $MESSAGEPACK_PORT
      MCAST_IP: $MCAST_IP
      MCAST_PORT: $MCAST_PORT
  
  native-worker:
    build:
      context: serialization_worker/
      dockerfile: worker.Dockerfile
    command: python3 ./worker.py
    environment:
      METHOD: Native
      HOST: 0.0.0.0
      PORT: $NATIVE_PORT
      MCAST_IP: $MCAST_IP
      MCAST_PORT: $MCAST_PORT
  
  yaml-worker:
    build:
      context: serialization_worker/
      dockerfile: worker.Dockerfile
    command: python3 ./worker.py
    environment:
      METHOD: YAML
      HOST: 0.0.0.0
      PORT: $YAML_PORT
      MCAST_IP: $MCAST_IP
      MCAST_PORT: $MCAST_PORT
  
  xml-worker:
    build:
      context: serialization_worker/
      dockerfile: worker.Dockerfile
    command: python3 ./worker.py
    environment:
      METHOD: XML
      HOST: 0.0.0.0
      PORT: $XML_PORT
      MCAST_IP: $MCAST_IP
      MCAST_PORT: $MCAST_PORT
  
  avro-worker:
    build:
      context: serialization_worker/
      dockerfile: worker.Dockerfile
    command: python3 ./worker.py
    environment:
      METHOD: AVRO
      HOST: 0.0.0.0
      PORT: $AVRO_PORT
      MCAST_IP: $MCAST_IP
      MCAST_PORT: $MCAST_PORT
  
  proto-worker:
    build:
      context: serialization_worker/
      dockerfile: worker.Dockerfile
    command: python3 ./worker.py
    environment:
      METHOD: PROTO
      HOST: 0.0.0.0
      PORT: $PROTO_PORT
      MCAST_IP: $MCAST_IP
      MCAST_PORT: $MCAST_PORT

  proxy:
    build:
      context: proxy/
      dockerfile: proxy.Dockerfile
    command: python3 ./proxy.py
    environment:
      HOST: 0.0.0.0
      PORT: 4242
      JSON: $JSON_PORT
      MESSAGEPACK: $MESSAGEPACK_PORT
      NATIVE: $NATIVE_PORT
      YAML: $YAML_PORT
      XML: $XML_PORT
      AVRO: $AVRO_PORT
      PROTO: $PROTO_PORT
      MCAST_IP: $MCAST_IP
      MCAST_PORT: $MCAST_PORT
    ports: 
      - "4242:4242/udp"
    depends_on:
      - json-worker
      - messagepack-worker
      - native-worker
      - yaml-worker
      - xml-worker
      - avro-worker
      - proto-worker